Convert packaging script to MakD
sociomantic-tsunami/d1to2fix pull request #16
Opened 2016-12-22 18:25 UTC by leandro-lucarella-sociomantic

Also some other minor improvements to make files and build scripts.

2016-12-22 18:41 UTC, mihails-strasuns-sociomantic commented
Red :)

2016-12-22 18:42 UTC, leandro-lucarella-sociomantic commented
2nd try

2016-12-22 18:48 UTC, leandro-lucarella-sociomantic commented
:green_heart:

2016-12-22 18:50 UTC, mihails-strasuns-sociomantic requested changes

2016-12-22 18:50 UTC, mihails-strasuns-sociomantic commented on docker/ci.sh
> +make -r all
Title says `-n`. Whom to trust? :)

2016-12-23 02:34 UTC, leandro-lucarella-sociomantic commented on docker/ci.sh
> +make -r all
Code, my code is always perfect.

2016-12-23 02:35 UTC, leandro-lucarella-sociomantic commented
Updated commit message.

2016-12-24 21:20 UTC, mihails-strasuns-sociomantic approved these changes

2016-12-24 21:20 UTC, merged